const fs = require('fs');

const userLayout = {
  "cover": {
    "top": 25,
    "left": 10,
    "right": 10,
    "bgPosX": 50,
    "bgPosY": 50,
    "bottom": 25,
    "fontScale": 1,
    "bgSizeWidth": 125,
    "bgSizeHeight": 100,
    "bodyFontScale": 0.8,
    "bodyMarginTop": 12,
    "badgeFontScale": 0.7,
    "badgeMarginTop": 50,
    "bodyFontFamily": "Averia",
    "bodyTransformX": -3,
    "bodyTransformY": -155,
    "badgePaddingTop": 5,
    "bottomFontScale": 1.05,
    "headerMarginTop": 69,
    "badgePaddingLeft": 10,
    "bodyMarginBottom": -61,
    "bottomFontFamily": "Averia",
    "bottomTransformX": 1,
    "bottomTransformY": 0,
    "headerTransformX": 2,
    "headerTransformY": -23,
    "badgeMarginBottom": 0,
    "badgePaddingRight": 10,
    "badgePaddingBottom": 5,
    "headerMarginBottom": 31
  },
  "profile": {
    "top": 15,
    "left": 10,
    "right": 10,
    "bgPosX": 52,
    "bgPosY": 49,
    "bottom": 20,
    "avatarX": 3,
    "avatarY": -90,
    "fontScale": 1,
    "avatarScale": 130,
    "bgSizeWidth": 134,
    "bgSizeHeight": 100,
    "bodyFontColor": "#e81e61",
    "bodyFontScale": 2.4,
    "badgeFontScale": 1.2,
    "bodyTransformX": 4,
    "bodyTransformY": -91,
    "headerFontScale": 0.8,
    "bodyMarginBottom": 10,
    "bottomFontFamily": "Averia",
    "bottomTransformX": 4,
    "bottomTransformY": -86,
    "headerPaddingTop": 5,
    "headerTransformX": 2,
    "headerTransformY": -104,
    "headerPaddingLeft": 5,
    "badgePaddingBottom": 19,
    "bodyAnimationClass": "animate-pulse",
    "headerMarginBottom": 0,
    "headerPaddingRight": 5,
    "headerPaddingBottom": 5
  },
  "turut": {
    "top": 10,
    "left": 10,
    "right": 10,
    "bgPosX": 50,
    "bgPosY": 50,
    "bottom": 10,
    "fontScale": 1,
    "bgSizeWidth": 135,
    "bgSizeHeight": 105,
    "bodyTransformX": 2,
    "bodyTransformY": -215,
    "headerTransformX": 1,
    "headerTransformY": -211,
    "headerPaddingBottom": 15,
    "headerAnimationClass": "animate-pulse"
  },
  "event": {
    "top": 15,
    "left": 10,
    "right": 10,
    "bgPosX": 46,
    "bgPosY": 50,
    "bottom": 15,
    "fontScale": 1.1,
    "bgSizeWidth": 128,
    "bgSizeHeight": 101,
    "bodyFontFamily": "Averia",
    "bodyPaddingTop": 5,
    "bodyTransformX": -1,
    "bodyTransformY": -14,
    "countdownScale": 1.15,
    "bottomFontScale": 0.95,
    "headerFontColor": "#e81e61",
    "headerFontScale": 2.35,
    "bottomFontFamily": "Averia",
    "bottomPaddingTop": 5,
    "bottomTransformX": -5,
    "bottomTransformY": -171,
    "buttonTransformX": 0,
    "buttonTransformY": 118,
    "headerTransformX": -2,
    "headerTransformY": -8,
    "bodyPaddingBottom": 5,
    "headerMarginBottom": 8,
    "locationTransformX": -3,
    "locationTransformY": 86,
    "bottomPaddingBottom": 5,
    "countdownTransformX": -5,
    "countdownTransformY": 89,
    "headerPaddingBottom": 10,
    "headerAnimationClass": "animate-pulse"
  },
  "maps": {
    "top": 10,
    "left": 10,
    "right": 10,
    "bgPosX": 44,
    "bgPosY": 50,
    "bottom": 10,
    "fontScale": 1,
    "bgSizeWidth": 132,
    "bottomWidth": 109,
    "bgSizeHeight": 105,
    "bodyFontColor": "#e81e61",
    "bodyFontScale": 1.45,
    "bodyPaddingTop": 9,
    "bodyTransformX": 0,
    "bodyTransformY": -1,
    "bottomFontColor": "#000000",
    "bottomFontScale": 0.8,
    "headerFontScale": 0.8,
    "bottomFontFamily": "Averia",
    "bottomTransformX": -16,
    "bottomTransformY": 1,
    "headerPaddingTop": 5,
    "bodyPaddingBottom": 9,
    "headerPaddingLeft": 9,
    "bodyAnimationClass": "animate-pulse",
    "headerPaddingRight": 9,
    "headerPaddingBottom": 5
  },
  "activities": {
    "top": 10,
    "left": 10,
    "right": 10,
    "bgPosX": 44,
    "bgPosY": 50,
    "bottom": 10,
    "avatarX": -2,
    "avatarY": -1,
    "fontScale": 1,
    "bgSizeWidth": 132,
    "bottomWidth": 102,
    "bgSizeHeight": 105,
    "bodyFontColor": "#e81e61",
    "bodyFontScale": 1.35,
    "bodyPaddingTop": 10,
    "bottomFontScale": 0.85,
    "headerFontScale": 0.8,
    "bottomTransformX": 3,
    "bottomTransformY": 3,
    "headerPaddingTop": 5,
    "bodyPaddingBottom": 10,
    "headerPaddingLeft": 9,
    "bodyAnimationClass": "animate-pulse",
    "headerPaddingRight": 9,
    "headerPaddingBottom": 5
  },
  "gallery": {
    "top": 10,
    "left": 10,
    "right": 10,
    "bgPosX": 50,
    "bgPosY": 50,
    "bottom": 10,
    "fontScale": 1,
    "bgSizeWidth": 100,
    "bgSizeHeight": 100,
    "headerFontColor": "#e81e61",
    "headerMarginTop": 0,
    "bodyPaddingBottom": 5,
    "headerMarginBottom": 0,
    "headerPaddingBottom": 10,
    "headerAnimationClass": "animate-pulse"
  },
  "rsvp": {
    "top": 25,
    "left": 10,
    "right": 10,
    "bgPosX": 46,
    "bgPosY": 50,
    "bottom": 15,
    "fontScale": 1,
    "lineHeight": 1.5,
    "bgSizeWidth": 135,
    "bgSizeHeight": 105,
    "bodyFontScale": 0.7,
    "bodyFontFamily": "Averia",
    "bodyPaddingTop": 5,
    "headerFontColor": "#e81e61",
    "headerFontScale": 1.55,
    "headerTransformX": 0,
    "headerTransformY": -1,
    "bodyPaddingBottom": 4,
    "headerPaddingBottom": 4
  },
  "envelope": {
    "top": 10,
    "left": 10,
    "right": 10,
    "bgPosX": 57,
    "bgPosY": 34,
    "bottom": 15,
    "fontScale": 1,
    "bgSizeWidth": 135,
    "bottomWidth": 101,
    "bgSizeHeight": 105,
    "bodyFontColor": "#e81e61",
    "bodyPaddingTop": 10,
    "bottomFontScale": 0.95,
    "headerFontScale": 0.8,
    "bottomFontFamily": "Averia",
    "headerPaddingTop": 5,
    "bodyPaddingBottom": 5,
    "headerPaddingLeft": 9,
    "headerPaddingRight": 9,
    "headerPaddingBottom": 5
  },
  "checkin": {
    "top": 10,
    "left": 10,
    "right": 10,
    "bgPosX": 46,
    "bgPosY": 50,
    "bottom": 10,
    "fontScale": 1,
    "bgSizeWidth": 135,
    "bottomWidth": 105,
    "bgSizeHeight": 105,
    "bodyFontColor": "#e81e61",
    "bodyPaddingTop": 10,
    "bottomFontScale": 0.9,
    "headerFontScale": 0.85,
    "bottomFontFamily": "Averia",
    "bottomTransformX": -10,
    "bottomTransformY": 19,
    "headerPaddingLeft": 9,
    "headerPaddingRight": 9,
    "bottomPaddingBottom": 10
  },
  "closing": {
    "top": 15,
    "left": 10,
    "right": 10,
    "bgPosX": 50,
    "bgPosY": 50,
    "bottom": 15,
    "avatarX": -2,
    "avatarY": -2,
    "fontScale": 1,
    "avatarScale": 190,
    "bgSizeWidth": 122,
    "bgSizeHeight": 100,
    "bodyFontFamily": "Averia",
    "bodyTransformX": -1,
    "bodyTransformY": -8,
    "headerPaddingTop": 5,
    "headerTransformX": 0,
    "headerTransformY": -10,
    "bodyPaddingBottom": 12,
    "headerPaddingLeft": 5,
    "headerPaddingRight": 5,
    "headerPaddingBottom": 5,
    "headerAnimationClass": "animate-pulse"
  },
  "global": {
    "musicUrl": "https://drive.google.com/file/d/1dtuutyBPZnthZq-T5vDvARRjBiEjVGuQ/view?usp=drive_link"
  }
};

const filePath = 'src/app/sandbox-tema/[id]/page.tsx';
let content = fs.readFileSync(filePath, 'utf8');

for (let i = 1; i <= 8; i++) {
  const themeName = `DEFAULT_CONFIG_THEME_${i}`;
  const blockStartRegex = new RegExp(`const ${themeName}: ThemeConfig = \\{[\\s\\S]*?\\n\\};`, 'm');
  
  const match = content.match(blockStartRegex);
  if (!match) {
    console.log(`Could not find ${themeName}`);
    continue;
  }
  
  // Create replacement block string
  const replacementString = `const ${themeName}: ThemeConfig = ${JSON.stringify(userLayout, null, 2)};`;
  
  content = content.replace(match[0], replacementString);
  console.log(`Replaced ${themeName}`);
}

fs.writeFileSync(filePath, content, 'utf8');
console.log('Successfully synced birthday layouts.');
